# Generated by Django 3.2.9 on 2021-11-27 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='registration_date',
            new_name='create',
        ),
        migrations.AlterField(
            model_name='business',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='store_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('street', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('settlement', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
