# Generated by Django 3.2.9 on 2021-12-02 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_start_date'),
        ('users', '0003_auto_20211127_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': 'Customer addresses'},
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
