# Generated by Django 3.2.9 on 2021-12-02 00:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AlterField(
            model_name='business',
            name='avatar',
            field=models.ImageField(
                default='images/default.jpg', upload_to=users.models.get_business_avatar_path),
        ),
    ]
