# Generated by Django 3.2.9 on 2021-12-02 00:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211202_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcustomer',
            name='avatar',
            field=models.ImageField(default='images/default.jpg', upload_to=users.models.get_customer_avatar_path),
        ),
    ]
