# Generated by Django 3.2.9 on 2021-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211202_0237'),
        ('users', '0007_alter_registeredcustomer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcustomer',
            name='wishlist',
            field=models.ManyToManyField(to='items.Item'),
        ),
    ]
