# Generated by Django 3.2.9 on 2021-12-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211202_0237'),
        ('orders', '0005_auto_20211206_1945'),
        ('users', '0010_auto_20211206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='registeredcustomer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='items.Item'),
        ),
    ]
