# Generated by Django 3.2.9 on 2021-12-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211209_1702'),
        ('users', '0015_alter_customeraddress_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
