# Generated by Django 3.2.9 on 2021-12-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_items'),
        ('users', '0017_auto_20211209_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcustomer',
            name='cart',
        ),
        migrations.AddField(
            model_name='registeredcustomer',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
