# Generated by Django 3.2.9 on 2021-12-12 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211212_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredcustomer',
            name='saved_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customeraddress'),
        ),
    ]
