# Generated by Django 3.2.9 on 2021-12-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_registeredcustomer_saved_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Banned')], default='0', max_length=2),
        ),
    ]
