# Generated by Django 3.2.9 on 2021-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_business_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
