# Generated by Django 3.2.9 on 2021-12-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
