# Generated by Django 3.2.9 on 2021-11-27 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('count', models.IntegerField(default=0)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
