# Generated by Django 3.2.9 on 2021-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='create',
            new_name='created',
        ),
    ]
