# Generated by Django 3.2.9 on 2021-12-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_registeredcustomer_saved_address'),
        ('requests_', '0002_rename_create_returnrequest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
