# Generated by Django 3.2.9 on 2021-12-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_registeredcustomer_saved_address'),
        ('requests_', '0003_auto_20211216_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
    ]
