# Generated by Django 3.2.9 on 2021-12-17 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_business_approved'),
        ('items', '0012_review_user'),
        ('requests_', '0004_auto_20211216_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='users.business'),
        ),
    ]
