# Generated by Django 3.2.9 on 2021-12-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_review_user'),
        ('requests_', '0005_auto_20211217_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
