# Generated by Django 3.2.9 on 2021-12-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_', '0006_alter_returnrequest_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected'), ('4', 'Error')], default='4', max_length=2),
        ),
    ]
