# Generated by Django 3.2.9 on 2021-12-02 00:37

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20211127_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to=items.models.get_category_picture_path),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to=items.models.get_item_picture_path),
        ),
    ]
