# Generated by Django 3.2.9 on 2021-12-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_vender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vender',
            new_name='vendor',
        ),
    ]
