# Generated by Django 3.2.9 on 2021-12-12 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('grade', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('text', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
