# Generated by Django 3.2.9 on 2021-11-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
