# Generated by Django 3.2.9 on 2021-12-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order statuses'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
