# Generated by Django 3.2.9 on 2021-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211206_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='create',
            new_name='created',
        ),
    ]
