# Generated by Django 3.2.9 on 2021-12-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Shipped'), ('2', 'Ordered'), ('3', 'Delivered'), ('4', 'Processing'), ('5', 'In cart'), ('6', 'Error')], default='6', max_length=2),
        ),
    ]
